#!/usr/bin/env bash
#    ┏┓┳┓┏┓┏┓┳┓ ┏┓
#    ┃┃┣┫┃┃┣ ┃┃ ┣
#    ┣┛┛┗┗┛┻ ┻┗┛┗┛
#
# Universal shell profile (bash/fish/zsh compatible where possible)
# Author: You :)
# Dependencies: fzf, pywal (optional), highlight (for less), starship

# ------------------------
# PATHS
# ------------------------
export PATH="$HOME/.local/bin:$HOME/.local/bin/statusbar:$HOME/.local/bin/cron:$HOME/Applications:/var/lib/flatpak/exports/bin:$PATH"

# ------------------------
# DEFAULT PROGRAMS
# ------------------------
export EDITOR="nvim"
export TERMINAL="kitty"
export LOCATION="Memari"
export BROWSER="chromium"

# ------------------------
# XDG BASE DIRECTORIES
# ------------------------
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_DATA_HOME/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"

#-------------------------
# BAT COLORS
#-------------------------
export BAT_THEME=ansi

#------------------------
# FZF TMUX
# -----------------------
export FZF_TMUX=1

# ------------------------
# LESS + COLORS
# ------------------------
export DICS="/usr/share/stardict/dic/"
export LESS="R"
export LESS_TERMCAP_mb=$(printf '\e[1;31m')
export LESS_TERMCAP_md=$(printf '\e[1;36m')
export LESS_TERMCAP_me=$(printf '\e[0m')
export LESS_TERMCAP_so=$(printf '\e[30;44m') # black fg, blue bg
export LESS_TERMCAP_se=$(printf '\e[0m')
export LESS_TERMCAP_us=$(printf '\e[1;32m')
export LESS_TERMCAP_ue=$(printf '\e[0m')
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"

# ------------------------
# QT / JAVA / MOZILLA HINTS
# ------------------------
export QT_QPA_PLATFORMTHEME="gtk2"
export MOZ_USE_XINPUT2=1
export AWT_TOOLKIT="MToolkit wmname LG3D"
export _JAVA_AWT_WM_NONREPARENTING=1

#------------------------------
# AUTO-LOGIN
#------------------------------
if [ "$(tty)" = "/dev/tty1" ] && uwsm check may-start; then
    exec uwsm start hyprland-uwsm.desktop
fi
