#  ┳┓┳┳┓┏┓┳┓┳┳  ┏┓┏┓┏┓
#  ┃┃┃┃┃┣ ┃┃┃┃━━┃┃┃┫┃┫
#  ┻┛┛ ┗┗┛┛┗┗┛  ┗╋┗┛┗┛
#                     



[ui.window.box]
width = 400

[ui.window.box.scroll.list]
max_width = 400
min_width = 400
width = 400
max_height = 500

[ui.window.box.search]
hide = false
