#  ┏┓┏┓┏┳┓┏┳┓┓┏
#  ┗┓┣┫ ┃  ┃ ┗┫
#  ┗┛┛┗ ┻  ┻ ┗┛
#              



[general]
# Save the file after pressing enter
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-enter = ["save-to-file"]

# Font to use for text annotations
[font]
family = "Iosevka Nerd Font"
style = "Oblique"

# Custom colours for the colour palette
[color-palette]
# These will be shown in the toolbar for quick selection
palette = [
    "#00ffff",
    "#a52a2a",
    "#dc143c",
    "#ff1493",
    "#ffd700",
    "#008000",
]

# These will be available in the color picker as presets
# Leave empty to use GTK's default
custom = [
    "#00ffff",
    "#a52a2a",
    "#dc143c",
    "#ff1493",
    "#ffd700",
    "#008000",
]
